### Site Settings ###
title               : Simon Warta
description         : >-                               # >- means to ignore newlines until "url:"
  I build digital infrastructure,
  fell down the blockchain rabbit hole and
  feel comfortable there.

url                 : ""                                   # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                                   # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : webmaster128/webmaster128.github.io  # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
remote_theme        : YoussefRaafatNasry/portfolYOU@v2.0.0 # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : Simon Warta
  image             : /assets/foto.jpg
# behance           : your_username
# dribbble          : your_username
# email             : username@domain.com
# facebook          : your_username
  github            : webmaster128
# gitlab            : your_username
# instagram         : your_username
# linkedin          : your_username
  medium            : simonwarta
# soundcloud        : your_username
# spotify           : your_username
  stackoverflow     : 2013738
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : simon_warta
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
